### ISSUE TITLE
Why is `name-generator.js` minified?

### ISSUE THREAD

**Issue by Cobertos** [gxvr/Business-Name-Generator#1]
Just curious why it's minified, it'd be nice to be able to look at the original code.

**Comment by Cobertos** [comment]
Was able to unminify most of it, https://gist.github.com/Cobertos/e78d6dc0044ed67d038b4c7bca94b2f1

**Comment by gxvr** [comment]
> 
> 
> Just curious why it's minified, it'd be nice to be able to look at the original code.

Well someone else did and most part of the code I got from the internet. Unfortunately I lost original one.
