### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by MyNameIz** [gxvr/Business-Name-Generator#2]
Hi, Geofrey!
I was looking for a keywords based name generator on npm but has no results.
When I tried to search for any sources on github I've found your app nameland.xyz. 
I was really impressed with result list of names generated by your app. I'd like to reuse this generator functionality at my home project. 
Would it be too much trouble for you to share with me a source code of name generator function?
Thank you so much for any feedback!

**Comment by capsloq** [comment]
Hello @MyNameIz 

pretty sure this project is using
https://www.npmjs.com/package/@rstacruz/startup-name-generator
under the hood.

**Comment by gxvr** [comment]
Hello @MyNameIz  Wow pretty cool. Thanks for linking me to the project  repo. I will add the author on README
